adam_beta1: 0.9
adam_beta2: 0.999
alpha: 12
batch_size: 1280
cba_dropout: 0.3
config_files: ./config/
dataset: QKA
dcba_dropout: 0.8
decay_factor: 0.9
dropout: 0.3
eval_freq: 5
ffn_acti: relu
hidden_dims: 64
init_std: 0.02
lmsal_heads: 2
lmsals: 2
log_freq: 1
lr: 0.001
max_epochs: 1000
maxlen: 50
min_lr: 1.0e-06
'no': 1
output_dir: ./output
patience: 5
run_dir: ./run
sal_heads: 2
seed: 2023
weight_decay: 0.0
