adam_beta1: 0.9
adam_beta2: 0.999
alpha: 12
batch_size: 1280
cba_dropout: 0.8
config_files: ./config/
dataset: QKV
dcba_dropout: 0.6
decay_factor: 0.9
dropout: 0.6
eval_freq: 5
ffn_acti: relu
hidden_dims: 64
init_std: 0.02
lmsal_dropout: 0.5
lmsal_heads: 4
lmsals: 2
log_freq: 1
lr: 0.001
max_epochs: 1000
maxlen: 50
min_lr: 1.0e-06
'no': 1
output_dir: ./output
patience: 5
run_dir: ./run
sal_dropout: 0.8
sal_heads: 2
sals: 1
seed: 2023
tau: 1.0
tensorboard_on: false
weight_decay: 0.0
